"""empty message

Revision ID: 47edb3193a5c
Revises: 43ee73aeb601
Create Date: 2025-09-14 22:12:01.291637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47edb3193a5c'
down_revision = '43ee73aeb601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('join_time')

    # ### end Alembic commands ###
